<header>
  <h1>Administrace</h1>
</header>

<section>
  <p>Vítejte v administraci, jste přihlášeni jako <?= $user_name ?>, máte úroveň <?= $user_permissions ?> a vaše id je <?= $user_id ?></p>
  <?php if (!$user_permissions) : ?>
      <p>Nemáte administrátorská oprávnění, požádejte administrátora webu, aby vám je přidělil.</p>
  <?php endif ?>
  <h2><a href="editor">Editor článků</a></h2>
  <h2><a href="clanek">Seznam článků</a></h2>
  <h2><a href="administrace/odhlasit">Odhlásit</a></h2>
</section>
