<header>
  <h1>Administrace</h1>
</header>

<section>
  <p>Vítejte v administraci, jste přihlášeni jako <?= $user_name ?>, máte úroveň <?= $user_permissions ?> a vaše id je <?= $user_id ?></p>
  <?php if (!$user_permissions) : ?>
      <p>Nemáte administrátorská oprávnění, požádejte administrátora webu, aby vám je přidělil.</p>
  <?php endif ?>

    <a class="fancy-submit" href="editor">Editor článků</a>
    
    <a class="fancy-submit" href="administrace/odhlasit">Odhlásit</a>
</section>
