<header>
  <p class="gray">Autor: <?= $authorname ?> | <?= $date ?> <?= $archival ?></p>
  <h1 class="superheading"><?= $title ?></h1>
</header>
<section>
  <p class="perex"><b><?= $description ?></b></p>
  <div class="article-content"><?= $_content ?></div>

  <?php if ($permissions) : ?>
    <br />
    <a href="editor/<?= $url ?>">[Editovat]</a>
    <a style="float:right;" href="clanek/<?= $url ?>/odstranit">[Odstranit]</a>
  <?php endif ?>
</section>
