<header>
  <h1>Seznam článků</h1>
</header>

<section>
  <table>
  <?php foreach($articles as $article) : ?>
    <tr>
      <td>
        <h2><a href="clanek/<?= $article['article_url'] ?>"><?= $article['article_title'] ?></a></h2>
        <?= $article['article_description'] ?>
        <?php if ($user_permissions >= 1) : ?>
          <br />
          <a href="editor/<?= $article['article_url'] ?>">Editovat</a>
          <a href="clanek/<?= $article['article_url'] ?>/odstranit">Odstranit</a>
        <?php endif ?>
      </td>
    </tr>
  <?php endforeach ?>
  </table>
</section>
