<header>
  <div class="keywords">
    <?php foreach ($keywords as $keyword) : ?>
      <a class="keyword" href="<?= $keyword[1] ?>"><?= $keyword[0] ?></a>
    <?php endforeach ?>
  </div>
  <br />
  <br /><br />
  <p class="gray">Autor: <?= $authorname ?> | <?= $date ?><span style="float: right"><?= $archival ? 'Archivní' : '' ?></span></p>
  <h1 class="opensans"><?= $title ?></h1>
</header>
<section>
  <p class="perex"><b><?= $description ?></b></p><br />
  <div class="article-content"><?= $_content ?></div>

  <?php if ($permissions) : ?>
    <br />
    <a href="editor/<?= $url ?>">[Editovat]</a>
    <a style="float:right;" href="clanek/<?= $url ?>/odstranit">[Odstranit]</a>
  <?php endif ?>
</section>
