<header><h1>Kontaktní formulář</h1></header>
<section>
  <p>Kontaktujte nás odesláním formuláře níže.</p>

  <form method="post" id="form-email">
    <label for="target">Cíl</label><br />
    <select class="fancy-select" name="target" id="target">
      <option value="webmaster">Matěj</option>
      <option value="redaktor">Lazebník</option>
      <option value="vedouci">Bráca</option>
      <option value="audi">Audi</option>
    </select><br /><br />

    <label for="email">Vaše emailová adresa</label><br />
    <input class="fancy-input" type="email" id="email" name="email" required="required" value="<?= (isset($_POST['email'])) ? htmlspecialchars($_POST['email']) : '' ?>" /><br /><br />

    <label for="year">Antispam - zadejte aktuální rok</label><br />
    <input class="fancy-input" type="text" id="year" name="year" required="required" value="<?= (isset($_POST['year'])) ? htmlspecialchars($_POST['year']) : '' ?>"/><br /><br />

    <label for="message">Zpráva</label><br />
    <textarea required="required" class="fancy-areainput" id="message" name="message"><?= (isset($_POST['message'])) ? htmlspecialchars($_POST['message']) : '' ?></textarea><br /><br />

    <input class="fancy-submit" type="submit" name="send" value="Odeslat" />
  </form>
</section>

<header><h1>Adresa</h1></header>
<section>
  <p>Hvězdova 1716/2b, Nusle, 140 00 Praha</p>
  <p>bratskypetr@gmail.com 	602228008</p>
</section>
