<header>
  <h1>Editor článků</h1>
</header>

<section>
  <form method="post">
    <input type="hidden" name="article_id" value="<?= $article['article_id'] ?>" />
    <input type="hidden" name="article_author_id" value="<?= $article['article_author_id'] ?>" />

    <label for="article_title">Titulek</label><br />
    <h2><input type="text" id="article_title" name="article_title" class="fancy-input full-width" value="<?= $article['article_title'] ?>" /></h2><br /><br />

    <label for="article_description">Popis</label><br />
    <textarea class="fancy-areainput perex" id="article_description" name="article_description" rows="10"><?= $article['article_description'] ?></textarea><br /><br />

    <label for="article_keywords">Klíčová slova</label><br />
    <input type="text" id="article_keywords" name="article_keywords" class="fancy-input full-width" value="<?= $article['article_keywords'] ?>" /><br /><br />

    <label for="article_submitted_date">Datum</label><br />
    <input type="date" id="article_submitted_date" name="article_submitted_date" class="fancy-input" value="<?= $article['article_submitted_date'] ?>" /><br /><br />

    <label for="article_author_name">Autor</label><br />
    <input type="text" id="article_author_name" name="article_author_name" class="fancy-input" value="<?= $article['article_author_name'] ?>" /><br /><br />

    <textarea class="fancy-areainput" name="article_content"><?= $article['article_content'] ?></textarea>

    <input class="fancy-submit" type="submit" name="article_submit" value="Uložit článek" /><br />
  </form>
  <script src="https://cdn.tiny.cloud/1/g3bb2hnmstt85rymhiywlmv88qoywdyrfjpijqigew2i95sx/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>

  <script type="text/javascript">
  tinymce.init({
    selector: "textarea[name=article_content]",
    plugins: [
      "advlist autolink lists link image charmap print anchor",
      "searchreplace visualblocks code fullscreen",
      "insertdatetime media table contextmenu paste",
      "autolink lists media table"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
    entities: "160,nbsp",
    entity_encoding: "named",
    entity_encoding: "raw",
    height : "600",
    image_caption: true,
    content_css: "../style.css",
    content_style: "body { font-family: serif; }",
    // without images_upload_url set, Upload tab won't show up
    images_upload_url: 'models/UploadImage.php',

						// override default upload handler to simulate successful upload
						images_upload_handler: function (blobInfo, success, failure) {
							var xhr, formData;

							xhr = new XMLHttpRequest();
							xhr.withCredentials = false;
							xhr.open('POST', 'models/UploadImage.php');

							xhr.onload = function() {
								var json;

								if (xhr.status != 200) {
									failure('HTTP Error: ' + xhr.status);
									return;
								}

								json = JSON.parse(xhr.responseText);

								if (!json || typeof json.location != 'string') {
									failure('Invalid JSON: ' + xhr.responseText);
									return;
								}

								success(json.location);
							};

							formData = new FormData();
							formData.append('file', blobInfo.blob(), blobInfo.filename());

							xhr.send(formData);
						},
  });

  </script>
</section>
