<!DOCTYPE html>
<html lang="cs-cz">
    <head>
        <base href="/mvc" />
        <meta charset="UTF-8" />
        <title><?= $title ?> | SOVF</title>
        <meta name="description" content="<?= $description ?>" />
        <meta name="keywords" content="<?= $keywords ?>" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="style.css" type="text/css"/>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Garamond">

        <link rel="icon" href="images/SOVF_logo_RGB.png" type="image/x-icon">
    </head>

    <body>

        <nav class="navbar navbar-inverse navbar-sticky container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="clanek/uvod">SOVF</a>
          </div>
            <ul class="nav navbar-nav">
                <li><a href="clanek/uvod">Úvod</a></li>
                <li><a href="clanek">Články</a></li>
                <li><a href="kontakt">Kontakt</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
    		        <li><a href="administrace">Administrace</a></li>
    		    </ul>
        </nav>

        <div id="wrap">

        <div class="container clear-top" id="main">

          <div class="jumbotron text-center">
    <h1><b>Skautský oddíl</b></h1><h1><b>Velena Fanderlika</b></h1>
    <p><i>Před zlem nikdy neutíká skaut Velena Fanderlika!</i></p>
    </div>

        <article >
          <?php foreach ($_messages as $message) : ?>
              <?= $message ?>
          <?php endforeach ?>

          <?php $this->controller->printView(); ?>
        </article>

      </div>
    </div>
        <footer class="text-center footer">
            <p>&copy SOVF 2021‒<?= date('Y') ?></p>
        </footer>
    </body>
</html>
