<!DOCTYPE html>
<html lang="cs-cz">
    <head>
        <base href="/mvc" />
        <meta charset="UTF-8" />
        <title><?= $title ?></title>
        <meta name="description" content="<?= $description ?>" />
        <meta name="keywords" content="<?= $keywords ?>" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="style.css" type="text/css"/>
    </head>

    <body>

        <nav class="navbar navbar-inverse navbar-sticky container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="clanek/uvod">SOVF</a>
          </div>
            <ul class="nav navbar-nav">
                <li><a href="clanek/uvod">Úvod</a></li>
                <li><a href="clanek">Články</a></li>
                <li><a href="kontakt">Kontakt</a></li>
            </ul>
        </nav>
        <br clear="both" />

        <article class="container">
          <?php $this->controller->printView(); ?>
        </article>

        <footer class="text-center">
            <p>Pokus</p>
        </footer>
    </body>
</html>
