<header>
  <h1>Přihlášení</h1>
</header>

<section>
  <form method="post">
    <label for="username">Jméno</label><br />
    <input type="text" class="fancy-input" id="username" name="username" value="<?php if(isset($_POST['username'])) echo($_POST['username']); ?>"/><br /><br />

    <label for="password">Heslo</label><br />
    <input type="password" class="fancy-input" id="password" name="password" value="<?php if(isset($_POST['password'])) echo($_POST['password']); ?>"/><br /><br />

    <input type="submit" class="fancy-submit" name="login_submit" value="Přihlásit"/>

  </form>
  <p>Pokud ještě nemáte účet, <a href="registrace">zaregistrujte se</a>.</p>
</section>
