<header>
  <h1>Registrace</h1>
</header>
<section>
  <form method="post">
    <label for="username">Jméno</label><br />
    <input type="text" class="fancy-input" id="username" name="username" value="<?php if(isset($_POST['username'])) echo($_POST['username']); ?>"/><br /><br />

    <label for="password">Heslo</label><br />
    <input type="password" class="fancy-input" id="password" name="password" value="<?php if(isset($_POST['password'])) echo($_POST['password']); ?>"/><br /><br />

    <label for="password_again">Heslo znovu</label><br />
    <input type="password" class="fancy-input" id="password_again" name="password_again" value="<?php if(isset($_POST['password_again'])) echo($_POST['password_again']); ?>"/><br /><br />

    <label for="year">Aktuální rok (antispam)</label><br />
    <input type="text" class="fancy-input" id="year" name="year" value="<?php if(isset($_POST['year'])) echo($_POST['year']); ?>"/><br /><br />

    <input type="submit" class="fancy-submit" name="register_submit" value="Registrovat"/>

  </form>
</section>
